<nav class="navbar navbar-expand-lg  navbar-light style="background-color: #fbc7d4;"">
  
  <a class="navbar-brand" href="../php/index_jogadores.php">Palavra Secreta</a>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#Nav">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="Nav">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="../php/index_jogadores.php">Página Inicial
          <span class="sr-only">(current)</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="../php/perfil_jogador.php">Perfil</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="../php/jogar.php" onclick="jogar()">Jogar</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="../php/ranking.php">Quadro de líderes</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="../php/logout.php">Logout</a>
      </li>
    </ul>
  </div>
</nav>
