<nav class="navbar navbar-expand-lg  navbar-light style="background-color: #fbc7d4;"">
  
  <a class="navbar-brand" href="../php/index_admin.php">Palavra Secreta</a>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#Nav"
    aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="Nav">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="../php/index_admin.php">Página Inicial
          <span class="sr-only">(current)</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="../php/form_cadastro_palavra.php">Cadastro de palavras</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="../php/lista_palavra.php">Lista de palavras</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="../php/lista_usuarios.php">Lista de usuários</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Logout</a>
      </li>
    </ul>
  </div>
</nav>
