<footer class="page-footer font-small pt-4">
    <div class="container-fluid text-center text-md-left">
        <div class="row">
            <div class="col-md-6 mt-md-0 mt-3">
                <h5 class="text-uppercase ">Grupo 2 - Projeto Final</h5>
                <p>Jogo desenvolvido por Renan, Murilo, Vinicius e Matheus.</p>
            </div>
        </div>
    </div>
    <div class="footer-copyright text-center py-3">
        © 2019 IFSP - IEB
    </div>
</footer>
