<article>  
    <table class="table table-light table-striped table-hover" width="50%">
        <thead class="thead-dark">
            <tr>
                <th>Código</th>
                <th>Nome</th>
                <th>E-mail</th>
                <th>Senha</th>
                <th>Pontuação</th>
                <th>Jogos ganhos</th>
                <th>Jogos perdidos</th>
                <th>Troféu</th>
                <th>Alterar</th>
                <th>Excluir</th>
            </tr>
        </thead>
        <tbody>
            <?php
                lista_usuarios();
            ?>
        </tbody>
    </table>
</article>