<article>  
    <table class="table table-light table-striped table-hover" width="50%">
        <thead class="thead-dark">
            <tr>
                <th>Código</th>
                <th>Palavra</th>
                <th>Dica Genérica</th>
                <th>Dica Específica 1</th>
                <th>Dica Específica 2</th>
                <th>Alterar</th>
                <th>Excluir</th>
            </tr>
        </thead>
        <tbody>
            <?php
                lista_palavra();
            ?>
        </tbody>
    </table>
</article>